### ISSUE TITLE
Tensorflow and TensorflowLite

### ISSUE THREAD

**Issue by mh-ahmadii** [mtkarimi/persian-license-plate-recognition#12]
Hello! I'm wondering if it's possible to convert your PyTorch models into TensorFlow and then TensorFlow Lite models. I'd like to use them on Android phones but I'm not sure how to do the conversion. Any assistance would be much appreciated!

**Comment by mtkarimi** [comment]
instead of converting, please try to retrain the model this is better solution but if you truly decided to convert there is many solutions for it.


[Train for Yolov8](https://github.com/mtkarimi/persian-license-plate-recognition/tree/f7663563a1cd7bd6e3f5a3dbcf732902501ac973/iranis%20yolov8%20trainer)
